### ISSUE TITLE
Session loading at installation

### ISSUE THREAD

**Issue by wawax** [pluginsGLPI/escalade#1]
Original issue on redmine : https://forge.indepnet.net/issues/4072

PHP Notice: Undefined index: show_history in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\glpi\plugins\escalade\setup.php at line 16

cf : http://www.glpi-project.org/forum/viewtopic.php?id=30749

**Comment by orthagh** [comment]
Should be fixed in current master
