### ISSUE TITLE
Installation plugin KO

### ISSUE THREAD

**Issue by floriangrisolet** [pluginsGLPI/escalade#107]
Hello,

I've an error with the installation of escalade

Debug mode GLPI : 
PHP Compile Error (64): Cannot redeclare plugin_init_escalade() (previously declared in /var/www/html/glpi/marketplace/escalade/setup.php:43) in /var/www/html/glpi/plugins/escalade-2.7.0/setup.php at line 158

PHP Notice (8): Undefined index: show_history in /var/www/html/glpi/marketplace/escalade/setup.php at line 65

version GLPI : 9.5.5

Can you help me? 

Thank a lot

**Comment by btry** [comment]
Hi

I don't know well this plugin, then I can't answer accurately. You probably need to investigate in the source code, wait for someone else's answer or get help on the community forum : https://forum.glpi-project.org/
