### ISSUE TITLE
translation of escalation messages is not applied

### ISSUE THREAD

**Issue by thallestorchi** [pluginsGLPI/escalade#150]
After updating to a new version of the plugin escalade (2.8.3 > 2.9.1), ticket escalation messages are no longer translated into pt_BR (Brazilian Portuguese).

GLPI ver 10.0.9
escalade ver. 2.9.1

**Comment by stonebuzz** [comment]
I don't know why but the translation made by the community has disappeared

You can take part in the translation here

https://explore.transifex.com/teclib/glpi-project-plugin-escalade/

It will be added in the next release
