### ISSUE TITLE
Do not change group and return to another group

### ISSUE THREAD

**Issue by jardeljsv** [pluginsGLPI/escalade#152]
I have GLPI 10.0.9 and Scalade plugin 2.9.2 and when a Tchnician click on ícon  associate the ticket move to anther group, the same problema dont occurs when i change que configuration "Remove old assignment group in new group" to NO.

![image](https://github.com/pluginsGLPI/escalade/assets/72230557/d6ba1451-3343-441c-8a7c-0a7ce54c01db)

**Comment by stonebuzz** [comment]
I'm afraid I didn't understand your problem
