### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by obscandoble** [pluginsGLPI/escalade#17]
Hello!
I've downladed and installed this plugin and fin it very useful. 

So i've translated it to Russian with .po and .mo

Unfortunately, i can't attach these files here, and i not familiar with git as well

How can i transfer locale files?

**Comment by trasher** [comment]
Hello, and thank you for the translation :)

Translations should be done on http://transifex.com; I'm not a specialist, but you should be able to upload your PO files on it. MO files are re-generated, don't worry for those ones.
