### ISSUE TITLE
Bypass filtering when assigning groups not Working

### ISSUE THREAD

**Issue by mauriciolamego** [pluginsGLPI/escalade#171]
The existing groups in GLPI are not appearing for assignment, only those to which the technician is linked. Checking "ignore" should appear.
I have been using this resource for a long time e I know this resource.
Plugin Version 2.9.3

**Comment by mauriciolamego** [comment]
![image](https://github.com/pluginsGLPI/escalade/assets/40633272/0915c398-3268-4864-92ad-21098b4aca65)
![image](https://github.com/pluginsGLPI/escalade/assets/40633272/b42abe5c-e0b7-4e99-b676-8aa80217c281)

**Comment by stonebuzz** [comment]
Hi,

I confirm the bug, 

when no group is assigned to the ticket, the list of actors contains no group (we should have all the user's groups logged in).

as soon as a group is assigned, group filtering works correctly

**Comment by stonebuzz** [comment]
@mauriciolamego 

can you check  / test this ->  https://github.com/pluginsGLPI/escalade/pull/172

Best regards

**Comment by Critxtth** [comment]
> @mauriciolamego
> 
> can you check / test this -> #172
> 
> Best regards

Hi, I'm experiencing the same issue, I replaced the file with the one associated to the pull [#172 ](https://github.com/pluginsGLPI/escalade/pull/172), and it doesn't seem to work for me.

Waiting for @mauriciolamego 's answer though.

**Comment by stonebuzz** [comment]
I certainly misunderstood @mauriciolamego  comments

This does not call into question the PR, which is another problem.

I'm waiting for @mauriciolamego's reply to detail her problem

**Comment by mauriciolamego** [comment]
I made the changes, but it didn't have the expected effect. It still doesn't ignore the filter, keeping only the groups that the user belongs to.
version I'm working on is 2.9.3.
Enable group filtering enabled.
On selected user ignore group filtering.

**Comment by stonebuzz** [comment]
Hi @mauriciolamego 

can you try this -> https://github.com/pluginsGLPI/escalade/pull/174

**Comment by mauriciolamego** [comment]
Thanks for all.
It's work fine with -> https://github.com/pluginsGLPI/escalade/pull/174

**Comment by stonebuzz** [comment]
Hi @mauriciolamego 

Can you try this fix -> https://github.com/pluginsGLPI/escalade/pull/176

Best regards

**Comment by stonebuzz** [comment]
Fixes by https://github.com/pluginsGLPI/escalade/pull/176
