### ISSUE TITLE
Groups do not appear in suggestions when creating a ticket

### ISSUE THREAD

**Issue by Critxtth** [pluginsGLPI/escalade#173]
Hi,

I am not sure if this is the same issue as [this issue](https://github.com/pluginsGLPI/escalade/issues/171)
But it certainly look similar. 
I have recently updated GLPI from 10.0.10 to 10.0.12, and the escalade plugin to 2.9.3.
Since this update, I encounter a bug : I can't assign new tickets to a group that I'm not a member of. 

This is the expected behavior : 

![image](https://github.com/pluginsGLPI/escalade/assets/33840914/518a96ed-7b98-4599-821d-4c327a7bb89b)

This is the behavior after update : 

![image](https://github.com/pluginsGLPI/escalade/assets/33840914/f2d13c1e-14a2-4eae-8ebd-c5c82f8a40bc)

I haven't changed the config, it's always been the same but it doesn't work anymore after the update, even after trying the fix from this PR (which I thought was related, but maybe it is not) : https://github.com/pluginsGLPI/escalade/pull/172

Escalade config : 

![image](https://github.com/pluginsGLPI/escalade/assets/33840914/af3a24b1-8259-4cca-8707-0e6d5ca981a5)

 I will also add that I tried disabling all the other plugins and leave this one enabled only, and it doesn't change a thing.

**Comment by Critxtth** [comment]
FYI I tried fix #174 , and now I can't assign the ticket to anyone anymore because it's stuck in  loading :

![image](https://github.com/pluginsGLPI/escalade/assets/33840914/f880665f-694a-4067-9458-3d76a54d571c)

**Comment by stonebuzz** [comment]
can you check glpi log ?

**Comment by Critxtth** [comment]
> can you check glpi log ?

I have set 2 log files in the apache web server, the CustomLog combined gives me this log when I click on the "assign to"  drop down :

![image](https://github.com/pluginsGLPI/escalade/assets/33840914/5f13529c-861f-4608-8e3b-d6b201cb9174)

Are you looking for something else ? 

Observer and Creator field work fine by the way.

**Comment by Critxtth** [comment]
> Hi @Critxtth
> 
> can you test this PR -> #176
> 
> Best regards

Hi, thanks for your answer.

Ok so I replaced setup.php and /inc/group_group.class.php by the ones from #176 and ...
Maybe I am crazy or I did something wrong (I'm pretty certain I didn't) but this is what I have now :


 
![image](https://github.com/pluginsGLPI/escalade/assets/33840914/2f29b113-3504-4523-bb6c-99fdbba74f72)



I have this huge output in every composant of GLPI on every page, and it definitely comes from the new setup.php

**Comment by Critxtth** [comment]
Hi @stonebuzz thanks for your reply.

It doesn't seem to be working, now it does load the users but still not the groups.

Maybe I am not proceeding the right way, so I'll tell you what I do and you let me know if I do something wrong.

So I go check the PR you mentionned (#176) , and there I take the link to the files you changed, and proceed this way : 

`cd /var/www/html/glpi/plugins/escalade
mv setup.php setup.php.bkp
wget https://github.com/pluginsGLPI/escalade/blob/fbc2819cf35844420fbf8c6d6374ebe7f78ea02b/setup.php
chown apache.apache setup.php
chmod g+w setup.php
cd inc/
mv group_group.class.php group_group.class.php.bkp
wget https://github.com/pluginsGLPI/escalade/blob/fbc2819cf35844420fbf8c6d6374ebe7f78ea02b/inc/group_group.class.php
chown apache.apache group_group.class.php
chmod g+w group_group.class.php`

Is that correct or am I missing something ? 


Thanks in advance

**Comment by stonebuzz** [comment]
Hi @Critxtth 

we prefer to use patches (to make sure we apply all the changes without forgetting any)

Can you deliver version 2.9.3 (without any changes to the code)

Then, jJust apply this -> https://patch-diff.githubusercontent.com/raw/pluginsGLPI/escalade/pull/176.diff

With 

```shell
cd /var/www/html/glpi/marketplace/escalade/
patch -p1 < path_to_file.patch
```

Finally, logging out of GLPI,  clearing the cache with the following command 

```shell
cd /var/www/html/glpi/
php bin/console cache:clear
```

and then logging in again

**Comment by Critxtth** [comment]
> Hi @Critxtth
> 
> we prefer to use patches (to make sure we apply all the changes without forgetting any)
> 
> Can you deliver version 2.9.3 (without any changes to the code)
> 
> Then, jJust apply this -> https://patch-diff.githubusercontent.com/raw/pluginsGLPI/escalade/pull/176.diff
> 
> With
> 
> ```shell
> cd /var/www/html/glpi/marketplace/escalade/
> patch -p1 < path_to_file.patch
> ```
> 
> Finally, logging out of GLPI, clearing the cache with the following command
> 
> ```shell
> cd /var/www/html/glpi/
> php bin/console cache:clear
> ```
> 
> and then logging in again, and retry

Hi @stonebuzz ,

Following your procedure, it seems like it's working now 👍 
Thank you for your time !
