### ISSUE TITLE
Enhancement  - New option on the plugin configuration

### ISSUE THREAD

**Issue by andrepetinga** [pluginsGLPI/escalade#175]
Hello.
Could you add a config option to choose the default option for "Assign me as an observer" ??

![image](https://github.com/pluginsGLPI/escalade/assets/43515938/fa4441f0-ee9a-4e28-8988-0c085aa6e48a)

When we choose the escalate option, the "Assign me as an observer" option is activated by default and, in our case, we don't want to select it in 99% of the times.
So, with a config option on the plugin config, we just select "Disabled/Not selected" as the default option.

Thanks!!
Regards

**Comment by stonebuzz** [comment]
Hi 

The latest version allows you to define the behaviour (checked or unchecked by default)

![image](https://github.com/user-attachments/assets/952cc479-6315-4fde-ba37-b9f89e0a9922)
