### ISSUE TITLE
Traduction manquante dans la version 2.1.0

### ISSUE THREAD

**Issue by sebfun** [pluginsGLPI/escalade#18]
Bonjour
Certains textes ne sont pas traduits en français notamment dans la configuration du plugin sur la page 

Ex :
"a time of creation" et "a time of modification"

et enfin : "Display delete button of assigned suppliers"

Merci

**Comment by Harincka** [comment]
Bonjour, 

je pense avoir trouvé le problème, dans le fichier de traduction d'anglais à français c'est "at time of creation" et "at time of modification". La traduction ne s'effectue pas car il trouve pas le texte. Je peux modifier le fichier pour que ça traduise pour " a time of creation" mais je sais pas si vous voulez mettre "a time" ou "at time".

Cordialement Aurélien Harinck

**Comment by sebfun** [comment]
En anglais c'est bien "a time" mais du coup il faudrait mettre "pour l'heure de création" et "pour l'heure de modification" puisque ça suit la phrase "Prendre le groupe du technicien"

**Comment by trasher** [comment]
Bonjour,

La traduction a déjà été effecutée sur transifex (voir https://www.transifex.com/teclib/glpi-project-plugin-escalade/translate/) ; mais visiblement elles n'ont simplement pas été récupérées lors de la dernière release. Ce sera corrigé dans la prochaine.

**Comment by trasher** [comment]
Juste pour info, les traductions actuelles sont "Une date de création" et "Une date de modification".

**Comment by sebfun** [comment]
oui pas de souci j'avais proposé une idée mais vous mettez ce que vous voulez
