### ISSUE TITLE
Improvement request by entity

### ISSUE THREAD

**Issue by Windayz** [pluginsGLPI/escalade#181]
Hello,

Would it be possible to activate the plugin by entity and not for general use?
At the moment, this plugin is very useful for one entity but not for the others. As a result, for the others, the "escalate" button is still visible and I'd like to be able to hide it.

Thanks for your help!

**Comment by stonebuzz** [comment]
Hi @Windayz 

currently no, it requires a lot of work !

You may also consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal support or [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.
