### ISSUE TITLE
php error group assignment

### ISSUE THREAD

**Issue by Windayz** [pluginsGLPI/escalade#182]
When adding a group using the GLPI method (right-hand column), PHP errors occur :

![image](https://github.com/pluginsGLPI/escalade/assets/151719809/cce3e372-d659-48b6-854a-19ac2adc0547)

[2024-04-12 16:06:19] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "_from_assignment" in C:\GLPI\plugins\escalade\inc\ticket.class.php at line 44

**Comment by stonebuzz** [comment]
Please update to 2.9.5 (laready fix by https://github.com/pluginsGLPI/escalade/pull/186)

**Comment by Windayz** [comment]
From now on, I can't create a ticket from formcreator when the escalation plugin is activated... I get php errors!
