### ISSUE TITLE
error: change of status

### ISSUE THREAD

**Issue by jbudani** [pluginsGLPI/escalade#183]
Hello, I am having a problem since I updated glpi from 9.5 to 10.0.14, I have the escalation plugin installed and configured so that when assigning a new group of technicians to a ticket, it always goes to the "new" state, it works for all states, but not when the ticket is in new state, in this case, it puts it in "in progress" state.

In version 9.5 it worked correctly,
new status --> group change --> maintain new status
in progress --> group change --> change new status
standby --> group change --> change new status
solved --> change group --> change new status
closed --> group change --> change new status

thank you so much

Jorgelina

**Comment by stonebuzz** [comment]
Should be fixed since version 2.9.4

Please update your GLPI and plugins to the latest version.
