### ISSUE TITLE
No more closing the ticket when adding the solution

### ISSUE THREAD

**Issue by obreptice** [pluginsGLPI/escalade#189]
Hello,

After installing version 2.9.5, tickets do not close automatically. 
An error message appears "The mandatory fields are not defined. Please correct: Requester"
Although there is indeed a requester in the ticket.

Thanks.

**Comment by obreptice** [comment]
I downgraded to version 2.9.4 and the problem disappeared.

**Comment by stonebuzz** [comment]
Hi @obreptice 

can you try this -> https://github.com/pluginsGLPI/escalade/pull/192

**Comment by obreptice** [comment]
Hi,

It's ok

Thanks.
