### ISSUE TITLE
"Tickets to follow (climbed)" table in central page (group tab)

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/escalade#19]
This part shouldn't be displayed when the current profile doesn't have the Ticket::READALL right.

Displaying without this right implies some strange behaviors: 
- Forbidden access
- Different number of ticket in list

**Comment by stonebuzz** [comment]
Hi @orthagh 
it appears that it is already done in the last version of the plugin

I'm closing this issue, feel free to continue discussion here, or reopen issue if bug still happen.

Best regards
