### ISSUE TITLE
Problem since update 2.9.5 The plugin systematically deletes the requester and observer groups.

### ISSUE THREAD

**Issue by xseth03** [pluginsGLPI/escalade#190]
Hi, 

Problem since update 2.9.5
When a ticket goes to resolved. The plugin systematically deletes the requester and observer groups.

**Comment by Skududu** [comment]
Hi 
Same error here updated this morning, and now it delete the requester when we add a technician.

**Comment by Cyrilb42** [comment]
Hello,
Same issue for us

**Comment by Lainow** [comment]
Hello,

Can you test the above fix please ?

**Comment by Skududu** [comment]
Hello, 

It doesn't work

**Comment by stonebuzz** [comment]
Hi @Skududu 

Can you retry (commit have been added)

**Comment by stonebuzz** [comment]
related pull request -> https://github.com/pluginsGLPI/escalade/pull/192

**Comment by stonebuzz** [comment]
Fixed by #192
