### ISSUE TITLE
Suite 2.9.5, erreur sur champ Demandeur lors création ticket

### ISSUE THREAD

**Issue by Gaelolito** [pluginsGLPI/escalade#191]
Message d'erreur lors de la création d'un nouveau ticket (suite clic sur bouton Sauvegarder) : 
"Les champs obligatoires ne sont pas définis.
Merci de corriger : Demandeur"
Pourtant l'utilisateur Demandeur est renseigné et enregistré.
Le ticket est créé malgré tout et il est visible dans la liste des tickets de l'utilisateur Demandeur.
Il s'agit d'un message "incorrect".

**Comment by Gaelolito** [comment]
Autre constat sur ticket déjà créé :
Message d'erreur identique lors de clic sur l'icône en forme de personnage (à côté du champ "Attribué à") + le technicien n'est pas enregistré.
Par contre, le technicien est enregistré sans message d'erreur lorsqu'il est saisi manuellement dans ce champ.

**Comment by stonebuzz** [comment]
Hi @Gaelolito 

can you try this -> https://github.com/pluginsGLPI/escalade/pull/192

**Comment by stonebuzz** [comment]
Can you retry (commit have been added)

**Comment by Gaelolito** [comment]
Hi @stonebuzz 
Hier, j'ai downgradé en 2.9.4, donc pas de test avec modification du code dans fichier ticket.class.php
Maintenant, upgrade en 2.9.5, puis 2 nouveaux tests :
1. création d'un nouveau ticket : toujours même message d'erreur après appui sur bouton Sauvegarder (ticket bien enregistré au nom de l'utilisateur Demandeur)
2. association à un ticket existant avec icône en forme de personnage : message d'erreur identique + pas d'enregistrement du technicien dans champ "Attribué à "

**Comment by Gaelolito** [comment]
Non,
dans champs obligatoires, j'ai "Demandeur", mais pas "Groupe Demandeur"
dans champs masqués, j'ai "Groupe Demandeur"
Je reprécise : aucune modification n'a été faite sur le fichier ticket.class.php

**Comment by stonebuzz** [comment]
Bonjour, 
Pourriez-vous refaire un test avec ce patch

https://patch-diff.githubusercontent.com/raw/pluginsGLPI/escalade/pull/192.diff

**Comment by stonebuzz** [comment]
Pensez également à vider le cache de GLPI

```php bin/console cache:clear```

**Comment by stonebuzz** [comment]
Si vou savez installé le plugin avec le marketplace, assurez-vous de patcher le bon dossier => ```glpi/marketplace/escalade/``` et non pas  ```glpi/plugins/escalade/```

**Comment by Gaelolito** [comment]
Bonjour,
Le patch a été appliqué sur 3 instances GLPI distinctes avec succès ce 16/05/2024 à partir de 18h30.
Les 2 erreurs signalées sont corrigées.
Le plugin Escalade est bien en version 2.9.5
Merci beaucoup.
