### ISSUE TITLE
Erreur PHP

### ISSUE THREAD

**Issue by Windayz** [pluginsGLPI/escalade#199]
Bonjour,

Toujours une erreur PHP dans la dernière version du plugin lors de la création d'un ticket via formcreator :

[2024-05-24 13:56:24] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "_actors" in C:\GLPI RECETTE\plugins\escalade\inc\ticket.class.php at line 92
  Backtrace :
  plugins\escalade\hook.php:420                      PluginEscaladeTicket::pre_item_update()
  src\Plugin.php:1680                                plugin_escalade_pre_item_update()
  src\CommonDBTM.php:1610                            Plugin::doHook()
  src\Item_Ticket.php:109                            CommonDBTM->update()
  src\CommonDBTM.php:1343                            Item_Ticket->post_addItem()
  ...lace\formcreator\inc\targetticket.class.php:928 CommonDBTM->add()
  ...place\formcreator\inc\formanswer.class.php:1004 PluginFormcreatorTargetTicket->save()
  ...place\formcreator\inc\formanswer.class.php:1238 PluginFormcreatorFormAnswer->generateTarget()
  src\CommonDBTM.php:1343                            PluginFormcreatorFormAnswer->post_addItem()
  marketplace\formcreator\ajax\formanswer.php:60     CommonDBTM->add()
  public\index.php:82                                require()

Merci à vous !

Bonne journée.

**Comment by wanderlage** [comment]
We are also having the same problem, it started on 05/24.

**Comment by andrepetinga** [comment]
I installed the 2.9.6 version and have the same error, but not related to FormCreator.
In my case is related to Mailgate.

[2024-07-10 11:38:13] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "_actors" in ...../marketplace/escalade/inc/ticket.class.php at line 92
  Backtrace :
  marketplace/escalade/hook.php:420                  PluginEscaladeTicket::pre_item_update()
  src/Plugin.php:1680                                plugin_escalade_pre_item_update()
  src/CommonDBTM.php:1616                            Plugin::doHook()
  src/Features/ParentStatus.php:162                  CommonDBTM->update()
  src/ITILFollowup.php:277                           ITILFollowup->updateParentStatus()
  src/CommonDBTM.php:1349                            ITILFollowup->post_addItem()
  src/MailCollector.php:956                          CommonDBTM->add()
  src/MailCollector.php:1923                         MailCollector->collect()
  src/CronTask.php:1027                              MailCollector::cronMailgate()
  front/cron.php:87                                  CronTask::launch()

If I stop Cron jobs, the error stops.

**Comment by Windayz** [comment]
Any news about this php error please?

**Comment by andrepetinga** [comment]
Today I updated to 2.9.8 version, and then applied 2 fixes: #219 and #212.

The mentioned errors are gone!

**Comment by Windayz** [comment]
Indeed, everything works.
After testing, I had the problem that the technician or the group would not delete itself on escalation.
After testing this: https://github.com/pluginsGLPI/escalade/pull/219 everything works :)
