### ISSUE TITLE
"Reassign the ticket to the original group" don't create task

### ISSUE THREAD

**Issue by BorisNovg** [pluginsGLPI/escalade#202]
GLPI 10.0.15
Escalade 2.9.6
When you click on the "Reassign the ticket to the original group" button, the task with the text "Escalation to the group Group1." is not created.

Steps To reproduce:
![escalade1](https://github.com/pluginsGLPI/escalade/assets/39726474/4e5a67b0-5a10-4389-a708-43306e324875)

Expected:
![escalade2](https://github.com/pluginsGLPI/escalade/assets/39726474/ecbbef8f-934b-4adb-94a9-64cd874fa2b8)

Wrong result:
The task with the text "Escalation to the group ... ." is not created.

**Comment by stonebuzz** [comment]
Hi @BorisNovg 

with latest version, can you try this -> https://github.com/pluginsGLPI/escalade/pull/230

Best regards

**Comment by BorisNovg** [comment]
stonebuzz, thank you!

Testing on a test virtual machine - I make a copy of the main server in a separate isolated network segment. GLPI 10.0.15.
---

Installing escalade version **prior** to your suggested patch - stonebuzz/escalade at 2d6e8ce 20240802 [Download ZIP](https://github.com/stonebuzz/escalade/archive/2d6e8cef57f588f29d07f3bbb3bc6fb7cd39db6c.zip)
The problem described in this request is reproduced, the test result - the yellow bar "Escalation to the group..." was not created.

Installing the escalade version **with** your suggested patch - stonebuzz/escalade at bd38490 20240827 [Download ZIP](https://github.com/stonebuzz/escalade/archive/bd384906a39523366dc35a5cf7dd501a31f6de28.zip)
The problem described in this request is **not reproduced**, the test result - the yellow bar "Escalation to the group..." was **created**.

---

Advanced Check - Installing last MASTER escalade version - pluginsGLPI/escalade at 9fa1761 20240828 [Download ZIP](https://github.com/pluginsGLPI/escalade/archive/9fa1761a39177161cfee73f878fa27d33e392e49.zip)
The problem described in this request is reproduced, the test result - the yellow bar "Escalation to the group..." was not created.

**Comment by BorisNovg** [comment]
Addition in connection with [comment](https://github.com/stonebuzz/escalade/blob/2d6e8cef57f588f29d07f3bbb3bc6fb7cd39db6c/inc/ticket.class.php#L550):

>                 '_plugin_escalade_no_history' => true, // Prevent a duplicated task to be added

 duplicated tasks with the proposed solution do not appear.
