### ISSUE TITLE
Tickets Without a Group

### ISSUE THREAD

**Issue by ltfarm** [pluginsGLPI/escalade#211]
We carried out tests up to the latest version of the plugin and found some issues related to the possibility of deleting groups. We illustrate this below.

![image](https://github.com/pluginsGLPI/escalade/assets/147453296/6a479a80-b155-49f4-a7e9-00003b25640a)

When we start the transfer process and insert the new group, the delete buttons are enabled at this point, allowing the user to frequently remove both groups, leaving the ticket unqueued.

We try training and mentoring; however, in a structure with many technicians, this error continues to recur. This means that the ticket is not linked to any group, being assigned only to the technician, which goes against the workflow of most GLPI users, as work increasingly depends on queues (groups).

I'm sharing this report to explore the possibility of implementing a restriction that prevents users from removing groups during the modification process, as you will always need to have at least one group assigned or block saving until you insert at least one group.

We want to thank you immensely for this project, the features added here helped a lot in the implementation and development of workflows.

**Comment by stonebuzz** [comment]
Hi @ltfarm 

can you retry with latest version ?

**Comment by stonebuzz** [comment]
Recent versions correct this issue.

I close this one

BR
