### ISSUE TITLE
dual notification on escalade

### ISSUE THREAD

**Issue by hcimadomo-procsi** [pluginsGLPI/escalade#213]
Hello,
glpi 10.0.15/escalade 2.9.7:
An escalation to a new group generate dual notification : one for the old group and on for the new group. The configuration for notification is "new group in assignees" and " groupe chargé du ticket" in destinataire.
any idea ?
BR

**Comment by Windayz** [comment]
Well, if you've set up the old and new groups to receive a notification, it's normal for them to do so, isn't it?

**Comment by DEF-IT** [comment]
Hello, since the update to GLPI 10.0.16 and escalade 2.9.7 we are facing nearly the same issue.
When a ticket is escalated to a new group, the system send the email twice to the new group.
In notification only "groupe chargé du ticket" is set for "New group in assignees"
It was working well prior to the update.

**Comment by Gaelolito** [comment]
Hello,
Same case with GLPI 10.0.16 / Escalade 2.9.7
When a ticket is escalated to a new group, the system send the email twice to the new group.
Parameter notification :
![2024-08-26 09_53_27-Notification - TIBCO_TKT_Nouveau Groupe Technicien - GLPI](https://github.com/user-attachments/assets/e5796f45-82eb-495a-8f0e-d2d547ee0367)
Thanks for your help

**Comment by hcimadomo-procsi** [comment]
> Well, if you've set up the old and new groups to receive a notification, it's normal for them to do so, isn't it?

No, the target of notification "new group in assigned" is "last group assigned". Same with "group assigned"
This work well with escalade version 2.9.4.

**Comment by hcimadomo-procsi** [comment]
same issue with 2.9.8.
BR

**Comment by stonebuzz** [comment]
Hi @hcimadomo-procsi , @DEF-IT , @Gaelolito , @Windayz 

can you retry by using "main" branch ?

**Comment by Windayz** [comment]
> Hi @hcimadomo-procsi , @DEF-IT , @Gaelolito , @Windayz
> 
> can you retry by using "main" branch ?

everything is working properly, I haven't detected any bugs yet.
except for one small detail: if a mandatory field hasn't been filled in and you change the technician group and validate, it gives you an error because you haven't filled in the mandatory field, but the plugin still displays the “escalate to...” bubble.
Otherwise, all's well.

**Comment by Windayz** [comment]
> @Windayz
> 
> can you open new issue for this ?

yes it's done sorry, in any case, no bug! :)

**Comment by Gaelolito** [comment]
> Hi @hcimadomo-procsi , @DEF-IT , @Gaelolito , @Windayz
> 
> can you retry by using "main" branch ?

Escalade 2.9.8
Destinataire : New group assignee
always 2 identical notifications sent to each technician in the group
![2024-09-04 11_33_28-File d'attente des notifications - GLPI](https://github.com/user-attachments/assets/f89a0562-c549-43a6-b6a9-5a94f2902a63)

**Comment by Windayz** [comment]
> always 2 identical notifications sent to each technician in the group

yes, I'm wide awake but he's right, there are two notifications sent.

**Comment by stonebuzz** [comment]
How do you climb :
- via the history
- via the list of actors (assigned)

**Comment by DEF-IT** [comment]
Hello, using version 2.9.9 still have double notification.

**Comment by Gaelolito** [comment]
Hello,
I have always double notification with 2.9.9

**Comment by DEF-IT** [comment]
Hello, it seems that commenting the line 413 of the ticket.class.php fix the problem.

**Comment by stonebuzz** [comment]
@DEF-IT no impact on other notifiactions?

@Gaelolito @Windayz @hcimadomo-procsi con you confirm ?

**Comment by DEF-IT** [comment]
> @DEF-IT no impact on other notifiactions?
> 
> @Gaelolito @Windayz @hcimadomo-procsi con you confirm ?

Well, it seems to work fine, despite the notification should only be the one for the escalated group not the one with both old group + new group. Old group are being notified while they don't need too.

This modification was provided by someone of infotel while troubleshooting another issue.

**Comment by Gaelolito** [comment]
I can't test until Monday
I'll keep you posted

**Comment by hcimadomo-procsi** [comment]
Hello DEF-IT,
i test with version 2.9.9 and comment line 413. It's not ok: The notification is send to the members of old group and the text of notification include both the new group and the old group.
The line 413 permit to send notification with good ext in notification and the members of new group.
The issue is that there is a notification event with the both group send before this line.
Best regards

**Comment by Gaelolito** [comment]
Hello,
Test with version 2.9.9 and comment line 413.
I still see 2 notifications sent to members of the new group assigned.
Best regards

**Comment by DEF-IT** [comment]
> Hello DEF-IT, i test with version 2.9.9 and comment line 413. It's not ok: The notification is send to the members of old group and the text of notification include both the new group and the old group. The line 413 permit to send notification with good ext in notification and the members of new group. The issue is that there is a notification event with the both group send before this line. Best regards

Strange behaviours, in our case the new group receive the notification, but the text of notification include both old & new as you.

**Comment by stonebuzz** [comment]
@DEF-IT @Gaelolito @Windayz @hcimadomo-procsi 

Can you try this -> https://github.com/pluginsGLPI/escalade/pull/253

Best regards

**Comment by Gaelolito** [comment]
Initial tests are conclusive.
Waiting for further tests to fully validate.
Thank you very much.

**Comment by Gaelolito** [comment]
I can confirm that the fix is OK for me.
Best regards 👍

**Comment by hcimadomo-procsi** [comment]
Hello,
Thank for you work . if we consider the issue for to send twice the same notification to a technician, it's ok.
But the issue is not really resolved for me: when we escalade from old group to newgroup, the technicians of old group and the technicians of new group receive the notification that include both the old group and the new group. (I use the balise ##ticket.assigntogroups##  for notification).
Glpi is 10.0.15.
esclade plugin is 2.9.9 
Best regards

**Comment by Windayz** [comment]
> Hello, Thank for you work . if we consider the issue for to send twice the same notification to a technician, it's ok. But the issue is not really resolved for me: when we escalade from old group to newgroup, the technicians of old group and the technicians of new group receive the notification that include both the old group and the new group. (I use the balise ##ticket.assigntogroups## for notification). Glpi is 10.0.15. esclade plugin is 2.9.9 Best regards

Did you apply the previous commit?

**Comment by hcimadomo-procsi** [comment]
i take 2.9.9 on github. Is this version include the commit.If not, can you precise the commit please ?

**Comment by Windayz** [comment]
> i take 2.9.9 on github. Is this version include the commit.If not, can you precise the commit please ?

https://github.com/pluginsGLPI/escalade/pull/253/commits/d83bdd1318e7bdafec68db1c8b4058b5716e8f5f

**Comment by stonebuzz** [comment]
version 2.9.9 predates the fix, so it is not part of this version

Please apply https://patch-diff.githubusercontent.com/raw/pluginsGLPI/escalade/pull/253.diff
