### ISSUE TITLE
Escalation each time the ticket is saved on 2.9.7

### ISSUE THREAD

**Issue by raregtp** [pluginsGLPI/escalade#215]
GLPI on version 10.0.15
Escalade on version 2.9.7

Escalations configured and operating normally while on 2.9.6.  Upgraded to 2.9.7 and whenver a ticket is saved, a new private escalation follow-up appears in the ticket history.  Verified this on a test/development version cloned from our production system.  Reverted both systems to 2.9.6 and the issue no longer occurs.

In the below screenshot, the three escalations to the IT Service Desk Queue were created by simply pressing the 'Save' button on the ticket.  The fourth escalation was just a test after reverting to 2.9.6.

![image](https://github.com/user-attachments/assets/1b717fb9-8ce7-475c-aab5-8e965fd572d3)

Below is the historical log for the above ticket.

![image](https://github.com/user-attachments/assets/01462179-3843-4090-ac87-19334f3afd88)

Let me know what questions you have.  Thanks!

**Comment by stonebuzz** [comment]
Hi @raregtp 

can you test this -> https://github.com/pluginsGLPI/escalade/pull/214

**Comment by raregtp** [comment]
Looks like #214 does in fact fix this.  Tested in dev environment and all looks good.  Thanks!

**Comment by andrepetinga** [comment]
Yes, I also tested and it works.

But I have other problems with this version -> #218 

Can you check please.

Thanks!

**Comment by obreptice** [comment]
Hi,

I use GLPI 10.0.16 and Escalade 2.9.7
When I modify the file "inc/ticket.class.php" according to #214
the "Ticket" tab of the ticket becomes completely white.

![Capture d'écran 2024-07-16 173827](https://github.com/user-attachments/assets/9d235e82-7c72-47d3-8b2e-538131b27636)
Thanks!
