### ISSUE TITLE
Une erreur interne est survenue - Undefined array key "assign"

### ISSUE THREAD

**Issue by Pieval44** [pluginsGLPI/escalade#217]
Bonjou rà tous , 

GLPI 10.0.16
Escalade 2.9.7
Formcreator 2.13.9

Erreur lors d'envoi d'un formulaire : Une erreur interne est survenue. Veuillez en informer l'administrateur.
Analyse console : Warning: Undefined array key "assign" in C:\xampp\htdocs\glpi_test\marketplace\escalade\inc\ticket.class.php on line 108

Si je desactive le plugin escalade, plus d'erreur.

Pouvez-vous m'aider ? 

Merci

**Comment by stonebuzz** [comment]
Hi @Pieval44 

can you retry with latest version ?

Best regards

**Comment by stonebuzz** [comment]
Fixed (I no longer reproduce)

I'm closing this one

**Comment by Pieval44** [comment]
it's OK
