### ISSUE TITLE
Escalation problem when saving tickets

### ISSUE THREAD

**Issue by mserpin** [pluginsGLPI/escalade#221]
Hello, following the last update each time we save the tickets an escalation is added. What we didn't have in previous versions. 
![image](https://github.com/user-attachments/assets/10220f0a-9b41-465f-99d4-052a75c4172d)
![image](https://github.com/user-attachments/assets/a619dc6a-a6b1-414c-9bf2-b73c9b18652f)

**Comment by stonebuzz** [comment]
already fixed by https://github.com/pluginsGLPI/escalade/pull/214

(not released yet !)
