### ISSUE TITLE
technician not deleted during escalation

### ISSUE THREAD

**Issue by Gaelolito** [pluginsGLPI/escalade#225]
After updating the plugin from 2.9.5 to 2.9.8, I lost a feature called "Delete technicians during an escalation".
The option is set to "Yes".
![2024-08-02 11_33_17-Escalades - GLPI](https://github.com/user-attachments/assets/396b5df2-8371-4d0e-a98c-eca10f058601)

Tests that did not result in the technician being removed : 
1. Set the option "Deletion of technicians during an escalation" to "No", then to "Yes".
2. Set the option "Pre-select me as a technician when creating a ticket" to "No" in Personalising my account.
3. Escalation of a ticket where the technician's name is different from mine: the technician associated with the ticket remains and my name is not added.

Illustration of the extra line in the history:
![2024-08-02 11_37_37-Ticket (# 9399) - Objet _ EDITION DEVIS AK TIBIZ - TITRE + SOUS-TOTAL - GLPI](https://github.com/user-attachments/assets/fad3bb84-135f-49ed-9b1a-db533103598a)

**Comment by sblanchouin** [comment]
Hi,

Same error here, and same settings

Thanks

**Comment by benoooo85** [comment]
Hello,
Same issue. 
GLPI 10.0.15
Escalation 2.9.8
Regards

**Comment by sblanchouin** [comment]
> Hi @benoooo85 @sblanchouin @Gaelolito
> 
> can you retry by using "main" branch ?
> 
> after testing, the recent PR corrected the problem

Yes, you've right, it's ok now for me.

**Comment by stonebuzz** [comment]
great =)
