### ISSUE TITLE
Escalation does not appear for the profile that only has the take ownership function

### ISSUE THREAD

**Issue by marcosdasilvaor** [pluginsGLPI/escalade#227]
The escalation function is not displayed in the call when the technician's profile does not have the assign function. 
And even changing it to assign, only the groups in which the technician is part of appear.

![image](https://github.com/user-attachments/assets/7051e6a4-6cf5-424b-b67c-98a9519e4164)

![image](https://github.com/user-attachments/assets/45c9215c-c7b5-4588-b58c-3977b18719bc)

In version 2.9.2 it works perfectly for profiles that only have the steal function. Technicians are able to escalate to a second-level group

![image](https://github.com/user-attachments/assets/d318f408-4da7-4b27-a225-4bffce18f467)

![image](https://github.com/user-attachments/assets/613f1567-8933-44b6-b3b3-efaaeba05fe9)

The objective is to prevent a technician from assigning the call to another person without escalation. Or they can only assign it to another coach in the group.

**Comment by stonebuzz** [comment]
Hi @marcosdasilvaor 

If you don't have the right to assign, it is logical that you don't have the right to escalate (from timeline) (given that the Assigned Actor section is greyed out).
