### ISSUE TITLE
Statut don't update when escalate

### ISSUE THREAD

**Issue by sblanchouin** [pluginsGLPI/escalade#232]
Hi,

When I escalate a ticket, statut don't update. Here my settings

![image](https://github.com/user-attachments/assets/e4209155-9b53-4da6-a3f3-79493c72d1b5)

In my case, if I create a ticket, and escalate, before escalate, ticket is "new", and juste after escalate, ticket is "in progress".

GLPI 10.0.16
Escalades 2.9.8

Thanks !

**Comment by stonebuzz** [comment]
Hi @sblanchouin 

can you try this

https://github.com/pluginsGLPI/escalade/pull/234

**Comment by sblanchouin** [comment]
Hi 

Technician is succesfully removed, but status is still in progress after escalate

**Comment by sblanchouin** [comment]
Perfect ! You can close this issue ;)

Thanks @stonebuzz

**Comment by stonebuzz** [comment]
great =)
