### ISSUE TITLE
2.9.8 (main branch from 04/09/2024) - Requester/Observer is deleted (external account) when escalating

### ISSUE THREAD

**Issue by andrepetinga** [pluginsGLPI/escalade#241]
Hello all.

Just installed  the main branch of 2.9.8 (no patches added) and I have an issue regarding external observers:

If we have a requester or observer with an email (external user), the requester/observer email will be deleted if escalade using the Escalate button or the "up arrow" (escalade history).

**The requester/observer will stay if we escalade searching for the group.**

And we can see this on the LOGS:

Using the "up arrow" (escalade history):
```
[2024-09-04 15:24:03] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "alternative_email" in …/glpi/src/CommonITILObject.php at line 9884
  Backtrace :
  src/Ticket.php:1041                                CommonITILObject->transformActorsInput()
  src/CommonDBTM.php:1618                            Ticket->prepareInputForUpdate()
  marketplace/escalade/inc/ticket.class.php:509      CommonDBTM->update()
  marketplace/escalade/front/climb_group.php:40      PluginEscaladeTicket::climb_group()
  public/index.php:82                                require()
```

Using the Escalate button:

```
[2024-09-04 15:18:30] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "alternative_email" in …/glpi/src/CommonITILObject.php at line 9884
  Backtrace :
  src/Ticket.php:1041                                CommonITILObject->transformActorsInput()
  src/CommonDBTM.php:1618                            Ticket->prepareInputForUpdate()
  marketplace/escalade/front/ticket.form.php:70      CommonDBTM->update()
  public/index.php:82                                require()
```

**Comment by stonebuzz** [comment]
Hi @andrepetinga 

can you try this -> https://github.com/pluginsGLPI/escalade/pull/244

**Comment by andrepetinga** [comment]
> Hi @andrepetinga
> 
> can you try this -> #244

Hello @stonebuzz.

Just picked up the 2.9.8 main branch and added your new line.

Perfect!! 

Both external email on requester and external email on Observer were not deleted after escalation using all 3 options (searching, Up arrow from history and using Escalade button).

Thanks again 👍
