### ISSUE TITLE
Escalade Contribution - Locales to Brazilian Portuguese

### ISSUE THREAD

**Issue by pedroluisvsousa** [pluginsGLPI/escalade#26]
Hi,

Follows my contribution to the translation of the Escalade-0.90-1.3 plugin to Brazilian Portuguese.

[locales-pt_BR-escalade-0.90-1.3.tar.gz](https://github.com/pluginsGLPI/escalade/files/852704/locales-pt_BR-escalade-0.90-1.3.tar.gz)

Sincerely,

Pedro Sousa

**Comment by trasher** [comment]
Hello,

Than you for your contribution. Translations must be done on Transifex, see https://www.transifex.com/teclib/glpi-project-plugin-escalade/dashboard/.

As far as I can see, pr_BR is already there and is 100% translated. Will be in a future release.
