### ISSUE TITLE
Clone Ticket leave opening time initial

### ISSUE THREAD

**Issue by flavio-pessoa** [pluginsGLPI/escalade#27]
When you clone a ticket the date and time is the one of the opening of the initial ticket, being that when you clone it is a new ticket.

**Comment by stonebuzz** [comment]
Hi, @flavio-pessoa

like you say, this feature is called "clone" and clone exactly the initial ticket.

 If you want to refactor this part or add new option, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

I'm closing this issue, feel free to continue discussion here if you want.
