### ISSUE TITLE
Confilt avec le plugin Formulaire

### ISSUE THREAD

**Issue by Darkitty** [pluginsGLPI/escalade#28]
Bonjour,

Lors de la création d'un ticket via le plugin formulaire, le technicien qui doit y être associé l'est puis supprimé :

```
928904	07-04-2017 15:26	xxxxxx (yyy)	Utilisateur	Supprimer un lien avec un élément : xxxxxx (yyy)
928903	07-04-2017 15:26	xxxxxx (yyy)	Statut		Changement de En cours (Attribué) à Nouveau
928902	07-04-2017 15:26	xxxxxx (yyy)	Utilisateur	Ajout d'un lien avec un élément : xxxxxx (yyy)
```

Si le plugin Escalade est désactivé, l'assignation reste effective sur le ticket.

Une issue a également été ouverte sur leur dépôt : https://github.com/pluginsGLPI/formcreator/issues/574

Merci d'avance 👍

**Comment by Badoche1337** [comment]
see https://github.com/pluginsGLPI/escalade/pull/65
