### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by lexcorp** [pluginsGLPI/escalade#30]
My contribution, translate to spanish, these translations do not refresh or show them in the form, I do not know why:

Display delete button of assigned suppliers --> Mostrar el Botón de eliminación de los proveedores asignados
a time of creation --> en el momento de la creación
a time of modification --> en el momento de la modificación

[Translate_es_ES.tar.gz](https://github.com/pluginsGLPI/escalade/files/1082876/Translate_es_ES.tar.gz)

**Comment by trasher** [comment]
Hello,

First, please use transifex to add new strings, "a time of *" are not translated there (see https://www.transifex.com/teclib/glpi-project-plugin-escalade/dashboard/).

I've just tested on the develop branch. The first string no longer exists. As of the other ones, translation is OK when I add them in my working copy.
Is it possible you forget to re-compile MO files after you made your changes?

Anyways, please use transifex, new locales will reach a future release.
