### ISSUE TITLE
Failed to generate closed ticket surveys when there are linked ticks and marked "yes" field "Close cloned tickets at the same time"

### ISSUE THREAD

**Issue by 2017Marina** [pluginsGLPI/escalade#33]
We have two linked tickets (not "cloned") when the first ticket is closed, the survey is generated correspond to second ticket that continues to be assigned

**Comment by stonebuzz** [comment]
Hi @2017Marina , this feature is not available yet,
actually you can just close cloned tickets at the same time.

If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)


I'm closing this issue, feel free to continue discussion here if you want.

Best regards
