### ISSUE TITLE
Escalade filtré

### ISSUE THREAD

**Issue by githublivier** [pluginsGLPI/escalade#46]
Bonjour,

J'ai installé le plugin en V2.1.0 sur un GLPI en V9.1.3
Je n'arrive pas à filtrer l'escalade.
Je vais bien sur Groupe A --> Onglet escalade --> Escalade vers Groupe B
Je vais dans la configuration du plugin Activer le filtrage sur les groupes d'attribution = Oui

Lorsque je vais sur un ticket du Groupe A et que je clique sur l'icone pour réattribuer le ticket, je peux le faire vers l'ensemble des groupes.
Y a t il une configuration particulière à effectuer ?

**Comment by githublivier** [comment]
J'ai activer le filtrage sur la session utilisateur.
Cependant, lorsque j'essaie d'escalader le ticket, aucun groupe n'est affiché. Il ne me renvoie pas Groupe B dans mes choix possibles
D'avance merci

**Comment by stonebuzz** [comment]
Bonjour @githublivier 
pouvez-vous tester la PR suivante https://github.com/pluginsGLPI/escalade/pull/81
sur la dernière version du plugin ?

Bien cordialement

**Comment by githublivier** [comment]
Bonjour,

Je suis désolé de revenir vers vous que maintenant. 
Je suis en GLPI 9.4.6 et j'ai essayé d'appliquer la modification de code pour les lignes 124 et 125 :

`			checkDOMChange("*[name='_itil_assign[groups_id]'", function() {
			   var assign_select_dom_id = $("[name='_itil_assign[groups_id]']")[0].id;`

Je rencontre toujours le problème.
Merci par avance pour votre aide
