### ISSUE TITLE
Improve escalation history table

### ISSUE THREAD

**Issue by Badoche1337** [pluginsGLPI/escalade#61]
Hello,

I want to add some informations in escalation history table : 

- Previous group assigned (Group A)
- Counter of escalations between Group A (previous) and Group B (new assigned group)
- New search option : total number of escalations in one ticket
- New search option : total number of escalations in one ticket between 2 distincts groups

I'll submit a new PR right after this issue.

**Comment by cedric-anne** [comment]
Done in 2.4.0 (#62).
