### ISSUE TITLE
API GLPI

### ISSUE THREAD

**Issue by keha35** [pluginsGLPI/escalade#63]
Hello,

I'm using the API REST of GLPI and when i'm changing or deleting & adding new groups to tickets, the plugin doesn't historize the group.

The solution would be to add histories with the API, but we need to add profile for interact with the plugin in using the API.

**Comment by stonebuzz** [comment]
Hi @keha35 

I don't think you need to implement this part, the plugin itself should add the history.

It is also expected to work in CLI mode.

https://github.com/pluginsGLPI/escalade/blob/master/setup.php#L48

Can you retry with latest version of plugin ?

Best regards
