### ISSUE TITLE
Undefined variable $first_trace 

### ISSUE THREAD

**Issue by Synairgis** [pluginsGLPI/escalade#68]
Hey there, I'm currently running some on GLPI with the latest version 9.2.3 and the latest version of this plugin (2.3.3) and I keep getting this error:

> Undefined variable: first_trace in /var/www/html/glpi/plugins/escalade/inc/ticket.class.php at line 253

I checked the code and indeed, the variable just appears out of the blue. Even a search through the entire plugin folder doesn't turn up anything aside from the place where it's used at line 253. Am I missing something?

**Comment by cedric-anne** [comment]
Fixed in 2.4.0 by 6838a6b2461f65ed6a6ac9f9bf9de85f6eaabf9c.
