### ISSUE TITLE
I feel dumb... Please help me!

### ISSUE THREAD

**Issue by J-C-P** [pluginsGLPI/escalade#72]
Hello,

I just installed the plugin (v 2.3.3) on my GLPI (v 9.3.3).
We have three levels of support.

I don't understand how it is supposed to work.
First : If I add the Level 2 as escalation in the Level 1 group (Opn the Level 1 group settings, go to Escalation Tab and add Level 2), does it means I can send ticket from level 1 to level 2 or the opposite?

Second : I tried both ways and I can manage to see the escalation button in the ticket form. Do I need to make something else?

Sorry for my dumb question but I fell lost :-/

Thanks

**Comment by Sicoval31** [comment]
you are lucky .. i see nothing !

**Comment by stonebuzz** [comment]
Hi @J-C-P 
 due to #73, you will find a brief explanation of how it works 

I'm closing this ticket, so feel free to continue the discussion on #73
