### ISSUE TITLE
Pas d'affchage des flèches des anciens groupes attribués Version 2.4.1

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/escalade#76]
Hello,
Je viens de remarquer qu'il y a un soucis sur les images (Flèches vertes) permettant re réattribuer l'ancien groupe lors de l'ajout d'un nouveau:
 
![image](https://user-images.githubusercontent.com/6872020/53883538-8c142000-4019-11e9-8d92-51320668b13f.png)

Merci

**Comment by cedric-anne** [comment]
Fixed by #74 .
