### ISSUE TITLE
Erreur Plugin Escalade

### ISSUE THREAD

**Issue by cp61** [pluginsGLPI/escalade#78]
Bonjour, 

Suite à la mise à jour de GLPI en 9.4.2 et à la mise en place du plugin Escalade en 2.4.2, l'erreur suivante apparait dans le fichier php-errors.log

[2019-04-17 15:31:00] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: glpiID
  Backtrace :
  plugins\escalade\inc\config.class.php:283          
  plugins\escalade\setup.php:54                      PluginEscaladeConfig::loadInSession()
  inc\plugin.class.php:168                           plugin_init_escalade()
  inc\includes.php:104                               Plugin::load()
  front\cron.php:38                                  include()
  {"user":"@SRV-SIC"}

**Comment by cedric-anne** [comment]
Hi,

#79 should fix your problem.

Regards
