### ISSUE TITLE
Escalation Order

### ISSUE THREAD

**Issue by tamarindo90** [pluginsGLPI/escalade#80]
When I want to scale from one group to another, in the history figure that first assigns it and then removes the link to the previous one, can it be configured to be the other way around? because I'm having problems with notifications

![historyglpi](https://user-images.githubusercontent.com/51209462/59208067-bf1d0100-8b7e-11e9-835f-5fb554de312a.jpg)

**Comment by stonebuzz** [comment]
Hi @tamarindo90 ,
it's not a configuration issue,
when the user add a group on a ticket, GLPI uses a "hook" to inform plugins of the addition of a group.
it's at this time that the plugin "escalade" is aware of the addition so it can delete the old group.

A "hook" exist to inform plugins before add group on ticket, but
doing this action at this time does not ensure that the new group is added to the ticket (in the database).

If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)


I'm closing this issue, feel free to continue discussion here if you want.

Best regards
