### ISSUE TITLE
Ticket without a group don't show the groups' history

### ISSUE THREAD

**Issue by emaw705** [pluginsGLPI/escalade#82]
Hi.

I'm using the plugin and I activated the option "Display delete button -> Assigned To -> Group".

When I delete the active group, all the history desappeared. If then I assign a group again, the history is showed correctly.

**Comment by stonebuzz** [comment]
Hi @emaw705 
can test this PR 

https://github.com/pluginsGLPI/escalade/pull/84

Best regards

**Comment by emaw705** [comment]
Hi @stonebuzz 

I have changed the lines in js/escalade.js.php and it works fine, the history is always visible now.

Thanks a lot.

Best regards
