### ISSUE TITLE
Error: change of status of the ticket

### ISSUE THREAD

**Issue by rpauleau** [pluginsGLPI/escalade#87]
After the creation of a ticket if I assign a group to the ticket when saving, it changes the ticket status in "In progress"
In the plugin configuration: Ticket status after climbing -> New

I want that statut in New after I assign a group

**Comment by stonebuzz** [comment]
Hi 

thanks for opening new issue, 
can you give us your glpi version, plugin version

screenshot of your plugin configuration
Best regards

**Comment by rpauleau** [comment]
Glpi 9.4.4
Plugin 2.4.4

Its good with a business rules
=> Criteria : Group tech "Name of groupe"
=> Action : Status "New"

but it would be better with the plugin

**Comment by stonebuzz** [comment]
With glpi 9.4.5 and plugin 2.4.4 i can't reproduce your problem,

can you disable all plugins except escalade and retry ?

Best regards

**Comment by rpauleau** [comment]
I try but with formcreator enable (I cant disable formcreator) and its not ok
I switch group tech and my ticket change to "in progress"

**Comment by stonebuzz** [comment]
you may have a rule about tickets which update states?
