### ISSUE TITLE
Problem with status after escalade

### ISSUE THREAD

**Issue by ales-infotel** [pluginsGLPI/escalade#93]
Hi,
I have a problem with the option "ticket status after escalade". If this config is set to "new". On a ticket with the new status if we escalade the ticket, the status after esalade is Processing (assigned).

I found a fix to this is to add following lines in ticket.class.php at the end of item_update function :

if (isset($item->input['_itil_assign']['groups_id']) &&
          $_SESSION['plugins']['escalade']['config']['ticket_last_status'] != -1) {
         $tickets_id = $item->input['id'];
         $ticket     = new Ticket();
         $ticket->update([
                            'id'     => $tickets_id,
                            'status' => $_SESSION['plugins']['escalade']['config']['ticket_last_status']]);
      }

**Comment by SuporteTalk** [comment]
Tried put your code on my installation and not worked. i have the same issue here, the ticket always go with processing status to next escalation group.

**Comment by SuporteTalk** [comment]
I did this changes on your code and worked for me

if ($_SESSION['plugins']['escalade']['config']['ticket_last_status'] != -1) {
      $tickets_id = $item->input['id'];
      $ticket = new Ticket();
      $ticket->update([
         'id' => $tickets_id,
         'status' => '1']);
      }

**Comment by stonebuzz** [comment]
Hi @ales-infotel @SuporteTalk 

can you try this -> https://github.com/pluginsGLPI/escalade/pull/164

Best regards

**Comment by sblanchouin** [comment]
Hi

Same here, @stonebuzz I test your suggestion and modify front/ticket.form.php and inc/ticket.class.php, but this cause a bug when I want to see or create a ticket (the middle of page is empty)

**Comment by stonebuzz** [comment]
Can you check your changes , maybe a Bad copy paste

**Comment by sblanchouin** [comment]
You were right!

I have a new behavior now, when a technician assigns a ticket, it remains in the "new" status, it no longer changes to "in progress (assigned)"

**Comment by sblanchouin** [comment]
@stonebuzz sorry, but not totaly resolve :)

Since the change, I have a new behavior now, when a technician assigns a ticket, it remains in the "new" status, it no longer changes to "in progress (assigned)"

**Comment by stonebuzz** [comment]
@sblanchouin  can you try this #117

**Comment by sblanchouin** [comment]
Sorry @stonebuzz I don't understand what I have to do... Can you explain me ?

**Comment by stonebuzz** [comment]
sorry, bad copy paste

can you try this -> https://github.com/pluginsGLPI/escalade/pull/177

**Comment by sblanchouin** [comment]
Perfect ! Thank you !
